apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sample-app
  name: sample-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sample-app
    spec:
      containers:
        - image: ghcr.io/kenta872/fastapi-sample-clone/fastapi-sample-clone:beta
          name: fastapi-sample
          envFrom:
            - configMapRef:
                name: sample-app-configmap
            - secretRef:
                name: sample-app-secret
          resources: {}
status: {}
