apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: nakai-test
  namespace: argocd
spec:
  description: nakai test AppProject
  sourceRepos:
    - "*"
  destinations:
    - namespace: default
      server: https://kubernetes.default.svc