apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: nakai-test
  source:
    repoURL: https://github.com/kenta872/fastapi-sample-clone.git
    path: manifests/fastapi-sample
    targetRevision: beta
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}
